version: "3.9"
services: 

  get-amo:
    build: ./
    container_name: get-amo
    volumes:
      - .:/app
    ports:
      - 80:3000
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm i -g @nestjs/cli; npm install; npm run start:dev"
